# Generated by Django 2.0 on 2018-10-28 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='almanac',
            fields=[
                ('date', models.DateField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('cid', models.IntegerField()),
                ('c_name', models.CharField(max_length=250, primary_key=True, serialize=False)),
                ('no_credits', models.IntegerField()),
                ('no_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='criteria_ta',
            fields=[
                ('Criteria', models.IntegerField(primary_key=True, serialize=False)),
                ('Grade', models.IntegerField(null=True)),
                ('Count', models.IntegerField(null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.course')),
            ],
        ),
        migrations.CreateModel(
            name='duration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(max_length=250)),
                ('timeperiod', models.IntegerField(null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=250)),
                ('event_type', models.CharField(max_length=250)),
                ('date', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.almanac')),
            ],
        ),
        migrations.CreateModel(
            name='faculty',
            fields=[
                ('fid', models.IntegerField(primary_key=True, serialize=False)),
                ('day_1', models.CharField(max_length=30)),
                ('day_2', models.CharField(max_length=30)),
                ('day_3', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Faculty_Meetings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_no', models.IntegerField()),
                ('start_time', models.CharField(max_length=250)),
                ('end_time', models.CharField(max_length=250)),
                ('purpose', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='room',
            fields=[
                ('rid', models.IntegerField(primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=250)),
                ('availability_status', models.IntegerField()),
                ('capacity', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='schedule_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('present_date', models.DateField()),
                ('resc_date', models.DateField()),
                ('day', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('section_id', models.IntegerField(primary_key=True, serialize=False)),
                ('section_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='slot_timings',
            fields=[
                ('slot_no', models.IntegerField(primary_key=True, serialize=False)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('sid', models.IntegerField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=250)),
                ('student_middle_name', models.CharField(max_length=250)),
                ('student_last_name', models.CharField(max_length=250)),
                ('student_dob', models.DateField()),
                ('student_gender', models.CharField(max_length=250)),
                ('student_email', models.CharField(max_length=250)),
                ('student_mobile', models.CharField(max_length=15)),
                ('student_blood_group', models.CharField(max_length=250)),
                ('student_mother_tongue', models.CharField(max_length=250)),
                ('student_registered_year', models.DateField(max_length=100)),
                ('student_registered_degree', models.IntegerField()),
                ('student_registered_degree_duration', models.DateField()),
                ('student_cur_yearofstudy', models.DateField()),
                ('student_cur_sem', models.IntegerField()),
                ('student_academic_status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='student_course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.Student')),
            ],
        ),
        migrations.CreateModel(
            name='student_grade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.IntegerField()),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.Student')),
            ],
        ),
        migrations.CreateModel(
            name='ta_alloc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=250)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.course')),
                ('sid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.Student')),
            ],
        ),
        migrations.CreateModel(
            name='timetable',
            fields=[
                ('day', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('class_type', models.IntegerField(null=True)),
                ('c_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.course')),
                ('rid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.room')),
                ('slot_no', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.slot_timings')),
            ],
        ),
        migrations.AddField(
            model_name='schedule_history',
            name='slot_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.slot_timings'),
        ),
        migrations.AddField(
            model_name='room',
            name='slot_no',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.slot_timings'),
        ),
        migrations.AddField(
            model_name='course',
            name='fid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='a13.faculty'),
        ),
    ]
